version: 2
jobs:
  testjdk11:
    docker:
      - image: circleci/clojure:openjdk-11-lein
    steps:
      - checkout
      - run: lein test

  testjdk15:
    docker:
      - image: circleci/clojure:openjdk-15-lein-buster
    steps:
      - checkout
      - run: lein test

  publish:
    docker:
      - image: circleci/clojure:openjdk-11-lein
    steps:
      - checkout
      - run: lein deploy clojars


workflows:
  version: 2
  build-publish:
    jobs:
      - testjdk11
      - testjdk15
      - publish:
          requires:
            - testjdk11
            - testjdk15
          filters:
            branches:
              only: master