version: 2.1
jobs:
  test:
    docker:
      - image: circleci/clojure:openjdk-11-lein
    steps:
      - checkout
      - run: lein test

  publish-snapshot:
    branches:
      only:
        - master
    docker:
      - image: circleci/clojure:openjdk-11-lein
    steps:
      - checkout
      - run: lein deploy clojars