version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-lein
    steps:
      - checkout
      - run: lein test

  publish-snapshot:
    docker:
      - image: circleci/clojure:openjdk-11-lein
    steps:
      - checkout
      - run: lein deploy

  publish-release:
    docker:
      - image: circleci/clojure:openjdk-11-lein
    steps:
      - checkout
      - run: git config --global user.email "george.narroway@me.com"
      - run: git config --global user.name "George Narroway"
      - run: lein release :minor


workflows:
  version: 2
  build-publish:
    jobs:
      - build
      - publish-snapshot:
          requires:
            - build
          filters:
            branches:
              only: master
      - promote:
          type: approval
          requires:
            - publish-snapshot
      - publish-release:
          requires:
            - promote