version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-lein
    steps:
      - checkout
      - run: lein test

  deploy:
    docker:
      - image: circleci/clojure:openjdk-11-lein
    steps:
      - checkout
      - run: lein deploy clojars


workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master