version: 2
jobs:
  test:
    docker:
      - image: circleci/clojure:openjdk-11-lein
    steps:
      - checkout
      - run: lein test

  publish-snapshot:
    docker:
      - image: circleci/clojure:openjdk-11-lein
    steps:
      - checkout
      - run: lein deploy clojars