version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-lein
    steps:
      - checkout
      - run: lein test
      - persist_to_workspace:
          root: .
          paths: target

  publish:
    docker:
      - image: circleci/clojure:openjdk-11-lein
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/target
      - run: lein deploy clojars


workflows:
  version: 2
  build-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master